# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 514ff1871a5e5f8c3292241b0c5705e7d7978cd5bb7f7068bb99b351e373623ce4f26057eb080dc4ba6a32bb2a078c83f1a54ec2d6219bd461812212e121dee8

test:
  secret_key_base: 19d50c5a0d462628038b8653de37bcb3de98ab5151871b38041813a4f765dd370a4b4c7e5a48c6e2575be71961cf0ae43d3b1b0924a6a268038224528a299ab2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
